
spring:
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
