
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/dhcd"
    username: dhcd
    password: dhcd-db-password

  flyway:
    enabled: true
    url: "jdbc:postgresql://localhost:5432/dhcd"
    user: dhcd
    password: dhcd-db-password
#    default-schema: "
#    schemas: "ewz_kus"