
spring:
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/dhcd"
    username: dhcd
    password: dhcd-db-password

  flyway:
    enabled: true
    url: "jdbc:postgresql://localhost:5432/dhcd"
    user: dhcd
    password: dhcd-db-password
#    default-schema: "
#    schemas: "ewz_kus"