
spring:
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB


  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  flyway:
    enabled: false
